<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Label="Globals">
    <WebView2LoaderPreference>Dynamic</WebView2LoaderPreference>
  </PropertyGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <Platforms>AnyCPU;x64;x86</Platforms>
    <ApplicationIcon>Data\image\logo13.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <SignAssembly>False</SignAssembly>
    <PackAsTool>False</PackAsTool>
    <IncludeSymbols>False</IncludeSymbols>
    <AssemblyVersion>4.0.0.0</AssemblyVersion>
    <Copyright></Copyright>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Views\Debug\**" />
    <EmbeddedResource Remove="Views\Debug\**" />
    <None Remove="Views\Debug\**" />
    <Page Remove="Views\Debug\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Data\font\2.ttc" />
    <None Remove="Data\font\f1.ttc" />
    <None Remove="Data\font\G_R1.ttf" />
    <None Remove="Data\font\Roboto-Black.ttf" />
    <None Remove="Data\font\Roboto-BlackItalic.ttf" />
    <None Remove="Data\font\Roboto-Bold.ttf" />
    <None Remove="Data\font\Roboto-BoldItalic.ttf" />
    <None Remove="Data\font\Roboto-Italic.ttf" />
    <None Remove="Data\font\Roboto-Light.ttf" />
    <None Remove="Data\font\Roboto-LightItalic.ttf" />
    <None Remove="Data\font\Roboto-Medium.ttf" />
    <None Remove="Data\font\Roboto-MediumItalic.ttf" />
    <None Remove="Data\font\Roboto-Regular.ttf" />
    <None Remove="Data\font\Roboto-Thin.ttf" />
    <None Remove="Data\font\Roboto-ThinItalic.ttf" />
    <None Remove="Data\font\RobotoCondensed-Bold.ttf" />
    <None Remove="Data\font\RobotoCondensed-BoldItalic.ttf" />
    <None Remove="Data\font\RobotoCondensed-Italic.ttf" />
    <None Remove="Data\font\RobotoCondensed-Light.ttf" />
    <None Remove="Data\font\RobotoCondensed-LightItalic.ttf" />
    <None Remove="Data\font\RobotoCondensed-Regular.ttf" />
    <None Remove="Data\font\simsun.ttc" />
    <None Remove="Data\image\About.png" />
    <None Remove="Data\image\Advanced.png" />
    <None Remove="Data\image\CheckUpdate.png" />
    <None Remove="Data\image\cjf.png" />
    <None Remove="Data\image\Clienting.png" />
    <None Remove="Data\image\Community.png" />
    <None Remove="Data\image\Develop.jpg" />
    <None Remove="Data\image\Hosting.png" />
    <None Remove="Data\image\icon\daynight.png" />
    <None Remove="Data\image\icon\icon.zip" />
    <None Remove="Data\image\icon\info.png" />
    <None Remove="Data\image\icon\join.png" />
    <None Remove="Data\image\icon\log.png" />
    <None Remove="Data\image\icon\room.png" />
    <None Remove="Data\image\icon\rooming.png" />
    <None Remove="Data\image\icon\rooms.png" />
    <None Remove="Data\image\icon\root.png" />
    <None Remove="Data\image\icon\settings.png" />
    <None Remove="Data\image\icon\wnd_btn_back.png" />
    <None Remove="Data\image\icon\wnd_btn_close.png" />
    <None Remove="Data\image\icon\wnd_btn_max.png" />
    <None Remove="Data\image\icon\wnd_btn_min.png" />
    <None Remove="Data\image\icon\wnd_btn_normal.png" />
    <None Remove="Data\image\ind.png" />
    <None Remove="Data\image\kslj.png" />
    <None Remove="Data\image\lj.png" />
    <None Remove="Data\image\logo13.ico" />
    <None Remove="Data\image\N2NGO_Logo_GO.png" />
    <None Remove="Data\image\N2NGO_Logo_N2N.png" />
    <None Remove="Data\image\N2NGO_Logo_N2N_Border.png" />
    <None Remove="Data\image\N2NGO_Logo_Warpper.png" />
    <None Remove="Data\image\Preview.jpg" />
    <None Remove="Data\image\Release.jpg" />
    <None Remove="Data\image\rzfw.png" />
    <None Remove="Data\image\sz.png" />
    <None Remove="Data\FlagIcons\ad.svg" />
    <None Remove="Data\FlagIcons\ae.svg" />
    <None Remove="Data\FlagIcons\af.svg" />
    <None Remove="Data\FlagIcons\ag.svg" />
    <None Remove="Data\FlagIcons\ai.svg" />
    <None Remove="Data\FlagIcons\al.svg" />
    <None Remove="Data\FlagIcons\am.svg" />
    <None Remove="Data\FlagIcons\ao.svg" />
    <None Remove="Data\FlagIcons\aq.svg" />
    <None Remove="Data\FlagIcons\ar.svg" />
    <None Remove="Data\FlagIcons\as.svg" />
    <None Remove="Data\FlagIcons\at.svg" />
    <None Remove="Data\FlagIcons\au.svg" />
    <None Remove="Data\FlagIcons\aw.svg" />
    <None Remove="Data\FlagIcons\ax.svg" />
    <None Remove="Data\FlagIcons\az.svg" />
    <None Remove="Data\FlagIcons\ba.svg" />
    <None Remove="Data\FlagIcons\bb.svg" />
    <None Remove="Data\FlagIcons\bd.svg" />
    <None Remove="Data\FlagIcons\be.svg" />
    <None Remove="Data\FlagIcons\bf.svg" />
    <None Remove="Data\FlagIcons\bg.svg" />
    <None Remove="Data\FlagIcons\bh.svg" />
    <None Remove="Data\FlagIcons\bi.svg" />
    <None Remove="Data\FlagIcons\bj.svg" />
    <None Remove="Data\FlagIcons\bl.svg" />
    <None Remove="Data\FlagIcons\bm.svg" />
    <None Remove="Data\FlagIcons\bn.svg" />
    <None Remove="Data\FlagIcons\bo.svg" />
    <None Remove="Data\FlagIcons\bq.svg" />
    <None Remove="Data\FlagIcons\br.svg" />
    <None Remove="Data\FlagIcons\bs.svg" />
    <None Remove="Data\FlagIcons\bt.svg" />
    <None Remove="Data\FlagIcons\bv.svg" />
    <None Remove="Data\FlagIcons\bw.svg" />
    <None Remove="Data\FlagIcons\by.svg" />
    <None Remove="Data\FlagIcons\bz.svg" />
    <None Remove="Data\FlagIcons\ca.svg" />
    <None Remove="Data\FlagIcons\cc.svg" />
    <None Remove="Data\FlagIcons\cd.svg" />
    <None Remove="Data\FlagIcons\cf.svg" />
    <None Remove="Data\FlagIcons\cg.svg" />
    <None Remove="Data\FlagIcons\ch.svg" />
    <None Remove="Data\FlagIcons\ci.svg" />
    <None Remove="Data\FlagIcons\ck.svg" />
    <None Remove="Data\FlagIcons\cl.svg" />
    <None Remove="Data\FlagIcons\cm.svg" />
    <None Remove="Data\FlagIcons\cn.svg" />
    <None Remove="Data\FlagIcons\co.svg" />
    <None Remove="Data\FlagIcons\cr.svg" />
    <None Remove="Data\FlagIcons\cu.svg" />
    <None Remove="Data\FlagIcons\cv.svg" />
    <None Remove="Data\FlagIcons\cw.svg" />
    <None Remove="Data\FlagIcons\cx.svg" />
    <None Remove="Data\FlagIcons\cy.svg" />
    <None Remove="Data\FlagIcons\cz.svg" />
    <None Remove="Data\FlagIcons\de.svg" />
    <None Remove="Data\FlagIcons\dj.svg" />
    <None Remove="Data\FlagIcons\dk.svg" />
    <None Remove="Data\FlagIcons\dm.svg" />
    <None Remove="Data\FlagIcons\do.svg" />
    <None Remove="Data\FlagIcons\dz.svg" />
    <None Remove="Data\FlagIcons\ec.svg" />
    <None Remove="Data\FlagIcons\ee.svg" />
    <None Remove="Data\FlagIcons\eg.svg" />
    <None Remove="Data\FlagIcons\eh.svg" />
    <None Remove="Data\FlagIcons\er.svg" />
    <None Remove="Data\FlagIcons\es.svg" />
    <None Remove="Data\FlagIcons\et.svg" />
    <None Remove="Data\FlagIcons\fi.svg" />
    <None Remove="Data\FlagIcons\fj.svg" />
    <None Remove="Data\FlagIcons\fk.svg" />
    <None Remove="Data\FlagIcons\fm.svg" />
    <None Remove="Data\FlagIcons\fo.svg" />
    <None Remove="Data\FlagIcons\fr.svg" />
    <None Remove="Data\FlagIcons\ga.svg" />
    <None Remove="Data\FlagIcons\gb-eng.svg" />
    <None Remove="Data\FlagIcons\gb-nir.svg" />
    <None Remove="Data\FlagIcons\gb-sct.svg" />
    <None Remove="Data\FlagIcons\gb-wls.svg" />
    <None Remove="Data\FlagIcons\gb.svg" />
    <None Remove="Data\FlagIcons\gd.svg" />
    <None Remove="Data\FlagIcons\ge.svg" />
    <None Remove="Data\FlagIcons\gf.svg" />
    <None Remove="Data\FlagIcons\gg.svg" />
    <None Remove="Data\FlagIcons\gh.svg" />
    <None Remove="Data\FlagIcons\gi.svg" />
    <None Remove="Data\FlagIcons\gl.svg" />
    <None Remove="Data\FlagIcons\gm.svg" />
    <None Remove="Data\FlagIcons\gn.svg" />
    <None Remove="Data\FlagIcons\gp.svg" />
    <None Remove="Data\FlagIcons\gq.svg" />
    <None Remove="Data\FlagIcons\gr.svg" />
    <None Remove="Data\FlagIcons\gs.svg" />
    <None Remove="Data\FlagIcons\gt.svg" />
    <None Remove="Data\FlagIcons\gu.svg" />
    <None Remove="Data\FlagIcons\gw.svg" />
    <None Remove="Data\FlagIcons\gy.svg" />
    <None Remove="Data\FlagIcons\hk.svg" />
    <None Remove="Data\FlagIcons\hm.svg" />
    <None Remove="Data\FlagIcons\hn.svg" />
    <None Remove="Data\FlagIcons\hr.svg" />
    <None Remove="Data\FlagIcons\ht.svg" />
    <None Remove="Data\FlagIcons\hu.svg" />
    <None Remove="Data\FlagIcons\id.svg" />
    <None Remove="Data\FlagIcons\ie.svg" />
    <None Remove="Data\FlagIcons\il.svg" />
    <None Remove="Data\FlagIcons\im.svg" />
    <None Remove="Data\FlagIcons\in.svg" />
    <None Remove="Data\FlagIcons\io.svg" />
    <None Remove="Data\FlagIcons\iq.svg" />
    <None Remove="Data\FlagIcons\ir.svg" />
    <None Remove="Data\FlagIcons\is.svg" />
    <None Remove="Data\FlagIcons\it.svg" />
    <None Remove="Data\FlagIcons\je.svg" />
    <None Remove="Data\FlagIcons\jm.svg" />
    <None Remove="Data\FlagIcons\jo.svg" />
    <None Remove="Data\FlagIcons\jp.svg" />
    <None Remove="Data\FlagIcons\ke.svg" />
    <None Remove="Data\FlagIcons\kg.svg" />
    <None Remove="Data\FlagIcons\kh.svg" />
    <None Remove="Data\FlagIcons\ki.svg" />
    <None Remove="Data\FlagIcons\km.svg" />
    <None Remove="Data\FlagIcons\kn.svg" />
    <None Remove="Data\FlagIcons\kp.svg" />
    <None Remove="Data\FlagIcons\kr.svg" />
    <None Remove="Data\FlagIcons\kw.svg" />
    <None Remove="Data\FlagIcons\ky.svg" />
    <None Remove="Data\FlagIcons\kz.svg" />
    <None Remove="Data\FlagIcons\la.svg" />
    <None Remove="Data\FlagIcons\lb.svg" />
    <None Remove="Data\FlagIcons\lc.svg" />
    <None Remove="Data\FlagIcons\li.svg" />
    <None Remove="Data\FlagIcons\lk.svg" />
    <None Remove="Data\FlagIcons\lr.svg" />
    <None Remove="Data\FlagIcons\ls.svg" />
    <None Remove="Data\FlagIcons\lt.svg" />
    <None Remove="Data\FlagIcons\lu.svg" />
    <None Remove="Data\FlagIcons\lv.svg" />
    <None Remove="Data\FlagIcons\ly.svg" />
    <None Remove="Data\FlagIcons\ma.svg" />
    <None Remove="Data\FlagIcons\mc.svg" />
    <None Remove="Data\FlagIcons\md.svg" />
    <None Remove="Data\FlagIcons\me.svg" />
    <None Remove="Data\FlagIcons\mf.svg" />
    <None Remove="Data\FlagIcons\mg.svg" />
    <None Remove="Data\FlagIcons\mh.svg" />
    <None Remove="Data\FlagIcons\mk.svg" />
    <None Remove="Data\FlagIcons\ml.svg" />
    <None Remove="Data\FlagIcons\mm.svg" />
    <None Remove="Data\FlagIcons\mn.svg" />
    <None Remove="Data\FlagIcons\mo.svg" />
    <None Remove="Data\FlagIcons\mp.svg" />
    <None Remove="Data\FlagIcons\mq.svg" />
    <None Remove="Data\FlagIcons\mr.svg" />
    <None Remove="Data\FlagIcons\ms.svg" />
    <None Remove="Data\FlagIcons\mt.svg" />
    <None Remove="Data\FlagIcons\mu.svg" />
    <None Remove="Data\FlagIcons\mv.svg" />
    <None Remove="Data\FlagIcons\mw.svg" />
    <None Remove="Data\FlagIcons\mx.svg" />
    <None Remove="Data\FlagIcons\my.svg" />
    <None Remove="Data\FlagIcons\mz.svg" />
    <None Remove="Data\FlagIcons\na.svg" />
    <None Remove="Data\FlagIcons\nc.svg" />
    <None Remove="Data\FlagIcons\ne.svg" />
    <None Remove="Data\FlagIcons\nf.svg" />
    <None Remove="Data\FlagIcons\ng.svg" />
    <None Remove="Data\FlagIcons\ni.svg" />
    <None Remove="Data\FlagIcons\nl.svg" />
    <None Remove="Data\FlagIcons\no.svg" />
    <None Remove="Data\FlagIcons\np.svg" />
    <None Remove="Data\FlagIcons\nr.svg" />
    <None Remove="Data\FlagIcons\nu.svg" />
    <None Remove="Data\FlagIcons\nz.svg" />
    <None Remove="Data\FlagIcons\om.svg" />
    <None Remove="Data\FlagIcons\pa.svg" />
    <None Remove="Data\FlagIcons\pe.svg" />
    <None Remove="Data\FlagIcons\pf.svg" />
    <None Remove="Data\FlagIcons\pg.svg" />
    <None Remove="Data\FlagIcons\ph.svg" />
    <None Remove="Data\FlagIcons\pk.svg" />
    <None Remove="Data\FlagIcons\pl.svg" />
    <None Remove="Data\FlagIcons\pm.svg" />
    <None Remove="Data\FlagIcons\pn.svg" />
    <None Remove="Data\FlagIcons\pr.svg" />
    <None Remove="Data\FlagIcons\ps.svg" />
    <None Remove="Data\FlagIcons\pt.svg" />
    <None Remove="Data\FlagIcons\pw.svg" />
    <None Remove="Data\FlagIcons\py.svg" />
    <None Remove="Data\FlagIcons\qa.svg" />
    <None Remove="Data\FlagIcons\re.svg" />
    <None Remove="Data\FlagIcons\ro.svg" />
    <None Remove="Data\FlagIcons\rs.svg" />
    <None Remove="Data\FlagIcons\ru.svg" />
    <None Remove="Data\FlagIcons\rw.svg" />
    <None Remove="Data\FlagIcons\sa.svg" />
    <None Remove="Data\FlagIcons\sb.svg" />
    <None Remove="Data\FlagIcons\sc.svg" />
    <None Remove="Data\FlagIcons\sd.svg" />
    <None Remove="Data\FlagIcons\se.svg" />
    <None Remove="Data\FlagIcons\sg.svg" />
    <None Remove="Data\FlagIcons\sh.svg" />
    <None Remove="Data\FlagIcons\si.svg" />
    <None Remove="Data\FlagIcons\sj.svg" />
    <None Remove="Data\FlagIcons\sk.svg" />
    <None Remove="Data\FlagIcons\sl.svg" />
    <None Remove="Data\FlagIcons\sm.svg" />
    <None Remove="Data\FlagIcons\sn.svg" />
    <None Remove="Data\FlagIcons\so.svg" />
    <None Remove="Data\FlagIcons\sr.svg" />
    <None Remove="Data\FlagIcons\ss.svg" />
    <None Remove="Data\FlagIcons\st.svg" />
    <None Remove="Data\FlagIcons\sv.svg" />
    <None Remove="Data\FlagIcons\sx.svg" />
    <None Remove="Data\FlagIcons\sy.svg" />
    <None Remove="Data\FlagIcons\sz.svg" />
    <None Remove="Data\FlagIcons\tc.svg" />
    <None Remove="Data\FlagIcons\td.svg" />
    <None Remove="Data\FlagIcons\tf.svg" />
    <None Remove="Data\FlagIcons\tg.svg" />
    <None Remove="Data\FlagIcons\th.svg" />
    <None Remove="Data\FlagIcons\tj.svg" />
    <None Remove="Data\FlagIcons\tk.svg" />
    <None Remove="Data\FlagIcons\tl.svg" />
    <None Remove="Data\FlagIcons\tm.svg" />
    <None Remove="Data\FlagIcons\tn.svg" />
    <None Remove="Data\FlagIcons\to.svg" />
    <None Remove="Data\FlagIcons\tr.svg" />
    <None Remove="Data\FlagIcons\tt.svg" />
    <None Remove="Data\FlagIcons\tv.svg" />
    <None Remove="Data\FlagIcons\tw.svg" />
    <None Remove="Data\FlagIcons\tz.svg" />
    <None Remove="Data\FlagIcons\ua.svg" />
    <None Remove="Data\FlagIcons\ug.svg" />
    <None Remove="Data\FlagIcons\um.svg" />
    <None Remove="Data\FlagIcons\us.svg" />
    <None Remove="Data\FlagIcons\uy.svg" />
    <None Remove="Data\FlagIcons\uz.svg" />
    <None Remove="Data\FlagIcons\va.svg" />
    <None Remove="Data\FlagIcons\vc.svg" />
    <None Remove="Data\FlagIcons\ve.svg" />
    <None Remove="Data\FlagIcons\vg.svg" />
    <None Remove="Data\FlagIcons\vi.svg" />
    <None Remove="Data\FlagIcons\vn.svg" />
    <None Remove="Data\FlagIcons\vu.svg" />
    <None Remove="Data\FlagIcons\wf.svg" />
    <None Remove="Data\FlagIcons\ws.svg" />
    <None Remove="Data\FlagIcons\xk.svg" />
    <None Remove="Data\FlagIcons\ye.svg" />
    <None Remove="Data\FlagIcons\yt.svg" />
    <None Remove="Data\FlagIcons\za.svg" />
    <None Remove="Data\FlagIcons\zm.svg" />
    <None Remove="Data\FlagIcons\zw.svg" />
    <None Remove="Views\SubPages\Page3.xaml.cs.removed" />
    <None Remove="Views\SubPages\Page3.xaml.removed" />
  </ItemGroup>

  <ItemGroup>
    <COMReference Include="NETCONLib">
      <VersionMinor>0</VersionMinor>
      <VersionMajor>1</VersionMajor>
      <Guid>43e734ca-043d-4a70-9a2c-a8f254063d91</Guid>
      <Lcid>0</Lcid>
      <WrapperTool>tlbimp</WrapperTool>
      <Isolated>false</Isolated>
      <EmbedInteropTypes>true</EmbedInteropTypes>
    </COMReference>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Data\FlagIcons\ad.svg" />
    <Resource Include="Data\FlagIcons\ae.svg" />
    <Resource Include="Data\FlagIcons\af.svg" />
    <Resource Include="Data\FlagIcons\ag.svg" />
    <Resource Include="Data\FlagIcons\ai.svg" />
    <Resource Include="Data\FlagIcons\al.svg" />
    <Resource Include="Data\FlagIcons\am.svg" />
    <Resource Include="Data\FlagIcons\ao.svg" />
    <Resource Include="Data\FlagIcons\aq.svg" />
    <Resource Include="Data\FlagIcons\ar.svg" />
    <Resource Include="Data\FlagIcons\as.svg" />
    <Resource Include="Data\FlagIcons\at.svg" />
    <Resource Include="Data\FlagIcons\au.svg" />
    <Resource Include="Data\FlagIcons\aw.svg" />
    <Resource Include="Data\FlagIcons\ax.svg" />
    <Resource Include="Data\FlagIcons\az.svg" />
    <Resource Include="Data\FlagIcons\ba.svg" />
    <Resource Include="Data\FlagIcons\bb.svg" />
    <Resource Include="Data\FlagIcons\bd.svg" />
    <Resource Include="Data\FlagIcons\be.svg" />
    <Resource Include="Data\FlagIcons\bf.svg" />
    <Resource Include="Data\FlagIcons\bg.svg" />
    <Resource Include="Data\FlagIcons\bh.svg" />
    <Resource Include="Data\FlagIcons\bi.svg" />
    <Resource Include="Data\FlagIcons\bj.svg" />
    <Resource Include="Data\FlagIcons\bl.svg" />
    <Resource Include="Data\FlagIcons\bm.svg" />
    <Resource Include="Data\FlagIcons\bn.svg" />
    <Resource Include="Data\FlagIcons\bo.svg" />
    <Resource Include="Data\FlagIcons\bq.svg" />
    <Resource Include="Data\FlagIcons\br.svg" />
    <Resource Include="Data\FlagIcons\bs.svg" />
    <Resource Include="Data\FlagIcons\bt.svg" />
    <Resource Include="Data\FlagIcons\bv.svg" />
    <Resource Include="Data\FlagIcons\bw.svg" />
    <Resource Include="Data\FlagIcons\by.svg" />
    <Resource Include="Data\FlagIcons\bz.svg" />
    <Resource Include="Data\FlagIcons\ca.svg" />
    <Resource Include="Data\FlagIcons\cc.svg" />
    <Resource Include="Data\FlagIcons\cd.svg" />
    <Resource Include="Data\FlagIcons\cf.svg" />
    <Resource Include="Data\FlagIcons\cg.svg" />
    <Resource Include="Data\FlagIcons\ch.svg" />
    <Resource Include="Data\FlagIcons\ci.svg" />
    <Resource Include="Data\FlagIcons\ck.svg" />
    <Resource Include="Data\FlagIcons\cl.svg" />
    <Resource Include="Data\FlagIcons\cm.svg" />
    <Resource Include="Data\FlagIcons\cn.svg" />
    <Resource Include="Data\FlagIcons\co.svg" />
    <Resource Include="Data\FlagIcons\cr.svg" />
    <Resource Include="Data\FlagIcons\cu.svg" />
    <Resource Include="Data\FlagIcons\cv.svg" />
    <Resource Include="Data\FlagIcons\cw.svg" />
    <Resource Include="Data\FlagIcons\cx.svg" />
    <Resource Include="Data\FlagIcons\cy.svg" />
    <Resource Include="Data\FlagIcons\cz.svg" />
    <Resource Include="Data\FlagIcons\de.svg" />
    <Resource Include="Data\FlagIcons\dj.svg" />
    <Resource Include="Data\FlagIcons\dk.svg" />
    <Resource Include="Data\FlagIcons\dm.svg" />
    <Resource Include="Data\FlagIcons\do.svg" />
    <Resource Include="Data\FlagIcons\dz.svg" />
    <Resource Include="Data\FlagIcons\ec.svg" />
    <Resource Include="Data\FlagIcons\ee.svg" />
    <Resource Include="Data\FlagIcons\eg.svg" />
    <Resource Include="Data\FlagIcons\eh.svg" />
    <Resource Include="Data\FlagIcons\er.svg" />
    <Resource Include="Data\FlagIcons\es.svg" />
    <Resource Include="Data\FlagIcons\et.svg" />
    <Resource Include="Data\FlagIcons\fi.svg" />
    <Resource Include="Data\FlagIcons\fj.svg" />
    <Resource Include="Data\FlagIcons\fk.svg" />
    <Resource Include="Data\FlagIcons\fm.svg" />
    <Resource Include="Data\FlagIcons\fo.svg" />
    <Resource Include="Data\FlagIcons\fr.svg" />
    <Resource Include="Data\FlagIcons\ga.svg" />
    <Resource Include="Data\FlagIcons\gb-eng.svg" />
    <Resource Include="Data\FlagIcons\gb-nir.svg" />
    <Resource Include="Data\FlagIcons\gb-sct.svg" />
    <Resource Include="Data\FlagIcons\gb-wls.svg" />
    <Resource Include="Data\FlagIcons\gb.svg" />
    <Resource Include="Data\FlagIcons\gd.svg" />
    <Resource Include="Data\FlagIcons\ge.svg" />
    <Resource Include="Data\FlagIcons\gf.svg" />
    <Resource Include="Data\FlagIcons\gg.svg" />
    <Resource Include="Data\FlagIcons\gh.svg" />
    <Resource Include="Data\FlagIcons\gi.svg" />
    <Resource Include="Data\FlagIcons\gl.svg" />
    <Resource Include="Data\FlagIcons\gm.svg" />
    <Resource Include="Data\FlagIcons\gn.svg" />
    <Resource Include="Data\FlagIcons\gp.svg" />
    <Resource Include="Data\FlagIcons\gq.svg" />
    <Resource Include="Data\FlagIcons\gr.svg" />
    <Resource Include="Data\FlagIcons\gs.svg" />
    <Resource Include="Data\FlagIcons\gt.svg" />
    <Resource Include="Data\FlagIcons\gu.svg" />
    <Resource Include="Data\FlagIcons\gw.svg" />
    <Resource Include="Data\FlagIcons\gy.svg" />
    <Resource Include="Data\FlagIcons\hk.svg" />
    <Resource Include="Data\FlagIcons\hm.svg" />
    <Resource Include="Data\FlagIcons\hn.svg" />
    <Resource Include="Data\FlagIcons\hr.svg" />
    <Resource Include="Data\FlagIcons\ht.svg" />
    <Resource Include="Data\FlagIcons\hu.svg" />
    <Resource Include="Data\FlagIcons\id.svg" />
    <Resource Include="Data\FlagIcons\ie.svg" />
    <Resource Include="Data\FlagIcons\il.svg" />
    <Resource Include="Data\FlagIcons\im.svg" />
    <Resource Include="Data\FlagIcons\in.svg" />
    <Resource Include="Data\FlagIcons\io.svg" />
    <Resource Include="Data\FlagIcons\iq.svg" />
    <Resource Include="Data\FlagIcons\ir.svg" />
    <Resource Include="Data\FlagIcons\is.svg" />
    <Resource Include="Data\FlagIcons\it.svg" />
    <Resource Include="Data\FlagIcons\je.svg" />
    <Resource Include="Data\FlagIcons\jm.svg" />
    <Resource Include="Data\FlagIcons\jo.svg" />
    <Resource Include="Data\FlagIcons\jp.svg" />
    <Resource Include="Data\FlagIcons\ke.svg" />
    <Resource Include="Data\FlagIcons\kg.svg" />
    <Resource Include="Data\FlagIcons\kh.svg" />
    <Resource Include="Data\FlagIcons\ki.svg" />
    <Resource Include="Data\FlagIcons\km.svg" />
    <Resource Include="Data\FlagIcons\kn.svg" />
    <Resource Include="Data\FlagIcons\kp.svg" />
    <Resource Include="Data\FlagIcons\kr.svg" />
    <Resource Include="Data\FlagIcons\kw.svg" />
    <Resource Include="Data\FlagIcons\ky.svg" />
    <Resource Include="Data\FlagIcons\kz.svg" />
    <Resource Include="Data\FlagIcons\la.svg" />
    <Resource Include="Data\FlagIcons\lb.svg" />
    <Resource Include="Data\FlagIcons\lc.svg" />
    <Resource Include="Data\FlagIcons\li.svg" />
    <Resource Include="Data\FlagIcons\lk.svg" />
    <Resource Include="Data\FlagIcons\lr.svg" />
    <Resource Include="Data\FlagIcons\ls.svg" />
    <Resource Include="Data\FlagIcons\lt.svg" />
    <Resource Include="Data\FlagIcons\lu.svg" />
    <Resource Include="Data\FlagIcons\lv.svg" />
    <Resource Include="Data\FlagIcons\ly.svg" />
    <Resource Include="Data\FlagIcons\ma.svg" />
    <Resource Include="Data\FlagIcons\mc.svg" />
    <Resource Include="Data\FlagIcons\md.svg" />
    <Resource Include="Data\FlagIcons\me.svg" />
    <Resource Include="Data\FlagIcons\mf.svg" />
    <Resource Include="Data\FlagIcons\mg.svg" />
    <Resource Include="Data\FlagIcons\mh.svg" />
    <Resource Include="Data\FlagIcons\mk.svg" />
    <Resource Include="Data\FlagIcons\ml.svg" />
    <Resource Include="Data\FlagIcons\mm.svg" />
    <Resource Include="Data\FlagIcons\mn.svg" />
    <Resource Include="Data\FlagIcons\mo.svg" />
    <Resource Include="Data\FlagIcons\mp.svg" />
    <Resource Include="Data\FlagIcons\mq.svg" />
    <Resource Include="Data\FlagIcons\mr.svg" />
    <Resource Include="Data\FlagIcons\ms.svg" />
    <Resource Include="Data\FlagIcons\mt.svg" />
    <Resource Include="Data\FlagIcons\mu.svg" />
    <Resource Include="Data\FlagIcons\mv.svg" />
    <Resource Include="Data\FlagIcons\mw.svg" />
    <Resource Include="Data\FlagIcons\mx.svg" />
    <Resource Include="Data\FlagIcons\my.svg" />
    <Resource Include="Data\FlagIcons\mz.svg" />
    <Resource Include="Data\FlagIcons\na.svg" />
    <Resource Include="Data\FlagIcons\nc.svg" />
    <Resource Include="Data\FlagIcons\ne.svg" />
    <Resource Include="Data\FlagIcons\nf.svg" />
    <Resource Include="Data\FlagIcons\ng.svg" />
    <Resource Include="Data\FlagIcons\ni.svg" />
    <Resource Include="Data\FlagIcons\nl.svg" />
    <Resource Include="Data\FlagIcons\no.svg" />
    <Resource Include="Data\FlagIcons\np.svg" />
    <Resource Include="Data\FlagIcons\nr.svg" />
    <Resource Include="Data\FlagIcons\nu.svg" />
    <Resource Include="Data\FlagIcons\nz.svg" />
    <Resource Include="Data\FlagIcons\om.svg" />
    <Resource Include="Data\FlagIcons\pa.svg" />
    <Resource Include="Data\FlagIcons\pe.svg" />
    <Resource Include="Data\FlagIcons\pf.svg" />
    <Resource Include="Data\FlagIcons\pg.svg" />
    <Resource Include="Data\FlagIcons\ph.svg" />
    <Resource Include="Data\FlagIcons\pk.svg" />
    <Resource Include="Data\FlagIcons\pl.svg" />
    <Resource Include="Data\FlagIcons\pm.svg" />
    <Resource Include="Data\FlagIcons\pn.svg" />
    <Resource Include="Data\FlagIcons\pr.svg" />
    <Resource Include="Data\FlagIcons\ps.svg" />
    <Resource Include="Data\FlagIcons\pt.svg" />
    <Resource Include="Data\FlagIcons\pw.svg" />
    <Resource Include="Data\FlagIcons\py.svg" />
    <Resource Include="Data\FlagIcons\qa.svg" />
    <Resource Include="Data\FlagIcons\re.svg" />
    <Resource Include="Data\FlagIcons\ro.svg" />
    <Resource Include="Data\FlagIcons\rs.svg" />
    <Resource Include="Data\FlagIcons\ru.svg" />
    <Resource Include="Data\FlagIcons\rw.svg" />
    <Resource Include="Data\FlagIcons\sa.svg" />
    <Resource Include="Data\FlagIcons\sb.svg" />
    <Resource Include="Data\FlagIcons\sc.svg" />
    <Resource Include="Data\FlagIcons\sd.svg" />
    <Resource Include="Data\FlagIcons\se.svg" />
    <Resource Include="Data\FlagIcons\sg.svg" />
    <Resource Include="Data\FlagIcons\sh.svg" />
    <Resource Include="Data\FlagIcons\si.svg" />
    <Resource Include="Data\FlagIcons\sj.svg" />
    <Resource Include="Data\FlagIcons\sk.svg" />
    <Resource Include="Data\FlagIcons\sl.svg" />
    <Resource Include="Data\FlagIcons\sm.svg" />
    <Resource Include="Data\FlagIcons\sn.svg" />
    <Resource Include="Data\FlagIcons\so.svg" />
    <Resource Include="Data\FlagIcons\sr.svg" />
    <Resource Include="Data\FlagIcons\ss.svg" />
    <Resource Include="Data\FlagIcons\st.svg" />
    <Resource Include="Data\FlagIcons\sv.svg" />
    <Resource Include="Data\FlagIcons\sx.svg" />
    <Resource Include="Data\FlagIcons\sy.svg" />
    <Resource Include="Data\FlagIcons\sz.svg" />
    <Resource Include="Data\FlagIcons\tc.svg" />
    <Resource Include="Data\FlagIcons\td.svg" />
    <Resource Include="Data\FlagIcons\tf.svg" />
    <Resource Include="Data\FlagIcons\tg.svg" />
    <Resource Include="Data\FlagIcons\th.svg" />
    <Resource Include="Data\FlagIcons\tj.svg" />
    <Resource Include="Data\FlagIcons\tk.svg" />
    <Resource Include="Data\FlagIcons\tl.svg" />
    <Resource Include="Data\FlagIcons\tm.svg" />
    <Resource Include="Data\FlagIcons\tn.svg" />
    <Resource Include="Data\FlagIcons\to.svg" />
    <Resource Include="Data\FlagIcons\tr.svg" />
    <Resource Include="Data\FlagIcons\tt.svg" />
    <Resource Include="Data\FlagIcons\tv.svg" />
    <Resource Include="Data\FlagIcons\tw.svg" />
    <Resource Include="Data\FlagIcons\tz.svg" />
    <Resource Include="Data\FlagIcons\ua.svg" />
    <Resource Include="Data\FlagIcons\ug.svg" />
    <Resource Include="Data\FlagIcons\um.svg" />
    <Resource Include="Data\FlagIcons\us.svg" />
    <Resource Include="Data\FlagIcons\uy.svg" />
    <Resource Include="Data\FlagIcons\uz.svg" />
    <Resource Include="Data\FlagIcons\va.svg" />
    <Resource Include="Data\FlagIcons\vc.svg" />
    <Resource Include="Data\FlagIcons\ve.svg" />
    <Resource Include="Data\FlagIcons\vg.svg" />
    <Resource Include="Data\FlagIcons\vi.svg" />
    <Resource Include="Data\FlagIcons\vn.svg" />
    <Resource Include="Data\FlagIcons\vu.svg" />
    <Resource Include="Data\FlagIcons\wf.svg" />
    <Resource Include="Data\FlagIcons\ws.svg" />
    <Resource Include="Data\FlagIcons\xk.svg" />
    <Resource Include="Data\FlagIcons\ye.svg" />
    <Resource Include="Data\FlagIcons\yt.svg" />
    <Resource Include="Data\FlagIcons\za.svg" />
    <Resource Include="Data\FlagIcons\zm.svg" />
    <Resource Include="Data\FlagIcons\zw.svg" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Data\font\Roboto-Black.ttf" />
    <Resource Include="Data\font\Roboto-BlackItalic.ttf" />
    <Resource Include="Data\font\Roboto-Bold.ttf" />
    <Resource Include="Data\font\Roboto-BoldItalic.ttf" />
    <Resource Include="Data\font\Roboto-Italic.ttf" />
    <Resource Include="Data\font\Roboto-Light.ttf" />
    <Resource Include="Data\font\Roboto-LightItalic.ttf" />
    <Resource Include="Data\font\Roboto-Medium.ttf" />
    <Resource Include="Data\font\Roboto-MediumItalic.ttf" />
    <Resource Include="Data\font\Roboto-Regular.ttf" />
    <Resource Include="Data\font\Roboto-Thin.ttf" />
    <Resource Include="Data\font\Roboto-ThinItalic.ttf" />
    <Resource Include="Data\font\RobotoCondensed-Bold.ttf" />
    <Resource Include="Data\font\RobotoCondensed-BoldItalic.ttf" />
    <Resource Include="Data\font\RobotoCondensed-Italic.ttf" />
    <Resource Include="Data\font\RobotoCondensed-Light.ttf" />
    <Resource Include="Data\font\RobotoCondensed-LightItalic.ttf" />
    <Resource Include="Data\font\RobotoCondensed-Regular.ttf" />
    <Resource Include="Data\image\About.png" />
    <Resource Include="Data\image\Advanced.png" />
    <Resource Include="Data\image\CheckUpdate.png" />
    <Resource Include="Data\image\Clienting.png" />
    <Resource Include="Data\image\Community.png" />
    <Resource Include="Data\image\Develop.jpg" />
    <Resource Include="Data\image\Hosting.png" />
    <Resource Include="Data\image\icon\daynight.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Data\image\icon\info.png" />
    <Resource Include="Data\image\icon\join.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Data\image\icon\log.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Data\image\icon\room.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Data\image\icon\rooming.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Data\image\icon\rooms.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Data\image\icon\root.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Data\image\icon\settings.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Data\image\icon\wnd_btn_back.png" />
    <Resource Include="Data\image\icon\wnd_btn_close.png" />
    <Resource Include="Data\image\icon\wnd_btn_max.png" />
    <Resource Include="Data\image\icon\wnd_btn_min.png" />
    <Resource Include="Data\image\icon\wnd_btn_normal.png" />
    <Resource Include="Data\image\ind.png" />
    <Resource Include="Data\image\logo13.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Data\image\N2NGO_Logo_GO.png" />
    <Resource Include="Data\image\N2NGO_Logo_N2N.png" />
    <Resource Include="Data\image\N2NGO_Logo_N2N_Border.png" />
    <Resource Include="Data\image\N2NGO_Logo_Warpper.png" />
    <Resource Include="Data\image\Preview.jpg" />
    <Resource Include="Data\image\Release.jpg" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\N2Nmc_Protocol\N2Nmc_Protocol.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Data\BinRef\Windows\N2NmcClientUpdate.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\BinRef\Windows\n2n\edge.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\BinRef\Windows\n2n\edge.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\NewsOffline.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\TAP-Windows.zip">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\TapWindowsInstaller\9.21.2.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\TapWindowsInstaller\openvpn.cer">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\TapWindowsInstaller\x32\OemVista.inf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\TapWindowsInstaller\x32\tap0901.cat">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\TapWindowsInstaller\x32\tap0901.sys">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\TapWindowsInstaller\x32\tapinstall.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\TapWindowsInstaller\x64\OemVista.inf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\TapWindowsInstaller\x64\tap0901.cat">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\TapWindowsInstaller\x64\tap0901.sys">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\TapWindowsInstaller\x64\tapinstall.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\BinRef\Windows\WinIPBroadcast\WinIPBroadcast.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="TAP-Windows\9.21.2.exe">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="TAP-Windows\openvpn.cer">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="TAP-Windows\x32\OemVista.inf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="TAP-Windows\x32\tap0901.cat">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="TAP-Windows\x32\tap0901.sys">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="TAP-Windows\x32\tapinstall.exe">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="TAP-Windows\x64\OemVista.inf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="TAP-Windows\x64\tap0901.cat">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="TAP-Windows\x64\tap0901.sys">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="TAP-Windows\x64\tapinstall.exe">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\MainResc.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>MainResc.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\MainResc.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>MainResc.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Data\BinRef\Linux\" />
    <Folder Include="Data\BinRef\Windows\n2n\" />
    <Folder Include="Resources\MainResc\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\.editorconfig" Link=".editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="HandyControl" Version="3.5.1" />
    <PackageReference Include="MagicEffects" Version="1.0.0">
      <NoWarn>NU1701</NoWarn>
    </PackageReference>
    <PackageReference Include="SharpVectors" Version="1.8.4" />
  </ItemGroup>

</Project>
