<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Label="Globals">
    <WebView2LoaderPreference>Dynamic</WebView2LoaderPreference>
  </PropertyGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <Platforms>AnyCPU;x64;x86</Platforms>
    <ApplicationIcon>Data\image\logo13.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <SignAssembly>False</SignAssembly>
    <PackAsTool>False</PackAsTool>
    <IncludeSymbols>False</IncludeSymbols>
    <AssemblyVersion>4.0.0.0</AssemblyVersion>
    <Copyright></Copyright>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Views\Debug\**" />
    <EmbeddedResource Remove="Views\Debug\**" />
    <None Remove="Views\Debug\**" />
    <Page Remove="Views\Debug\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Data\font\2.ttc" />
    <None Remove="Data\font\f1.ttc" />
    <None Remove="Data\font\G_R1.ttf" />
    <None Remove="Data\font\simsun.ttc" />
    <None Remove="Data\image\About.png" />
    <None Remove="Data\image\Advanced.png" />
    <None Remove="Data\image\CheckUpdate.png" />
    <None Remove="Data\image\cjf.png" />
    <None Remove="Data\image\Clienting.png" />
    <None Remove="Data\image\Community.png" />
    <None Remove="Data\image\Develop.jpg" />
    <None Remove="Data\image\Hosting.png" />
    <None Remove="Data\image\icon\daynight.png" />
    <None Remove="Data\image\icon\icon.zip" />
    <None Remove="Data\image\icon\info.png" />
    <None Remove="Data\image\icon\join.png" />
    <None Remove="Data\image\icon\log.png" />
    <None Remove="Data\image\icon\room.png" />
    <None Remove="Data\image\icon\rooming.png" />
    <None Remove="Data\image\icon\rooms.png" />
    <None Remove="Data\image\icon\root.png" />
    <None Remove="Data\image\icon\settings.png" />
    <None Remove="Data\image\icon\wnd_btn_back.png" />
    <None Remove="Data\image\icon\wnd_btn_close.png" />
    <None Remove="Data\image\icon\wnd_btn_max.png" />
    <None Remove="Data\image\icon\wnd_btn_min.png" />
    <None Remove="Data\image\icon\wnd_btn_normal.png" />
    <None Remove="Data\image\ind.png" />
    <None Remove="Data\image\kslj.png" />
    <None Remove="Data\image\lj.png" />
    <None Remove="Data\image\logo13.ico" />
    <None Remove="Data\image\N2NGO_Logo_GO.png" />
    <None Remove="Data\image\N2NGO_Logo_N2N.png" />
    <None Remove="Data\image\N2NGO_Logo_N2N_Border.png" />
    <None Remove="Data\image\N2NGO_Logo_Warpper.png" />
    <None Remove="Data\image\Preview.jpg" />
    <None Remove="Data\image\Release.jpg" />
    <None Remove="Data\image\rzfw.png" />
    <None Remove="Data\image\sz.png" />
    <None Remove="Views\SubPages\Page3.xaml.cs.removed" />
    <None Remove="Views\SubPages\Page3.xaml.removed" />
  </ItemGroup>

  <ItemGroup>
    <COMReference Include="NETCONLib">
      <VersionMinor>0</VersionMinor>
      <VersionMajor>1</VersionMajor>
      <Guid>43e734ca-043d-4a70-9a2c-a8f254063d91</Guid>
      <Lcid>0</Lcid>
      <WrapperTool>tlbimp</WrapperTool>
      <Isolated>false</Isolated>
      <EmbedInteropTypes>true</EmbedInteropTypes>
    </COMReference>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Data\font\f1.ttc" />
    <Resource Include="Data\image\About.png" />
    <Resource Include="Data\image\Advanced.png" />
    <Resource Include="Data\image\CheckUpdate.png" />
    <Resource Include="Data\image\Clienting.png" />
    <Resource Include="Data\image\Community.png" />
    <Resource Include="Data\image\Develop.jpg" />
    <Resource Include="Data\image\Hosting.png" />
    <Resource Include="Data\image\icon\daynight.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Data\image\icon\info.png" />
    <Resource Include="Data\image\icon\join.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Data\image\icon\log.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Data\image\icon\room.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Data\image\icon\rooming.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Data\image\icon\rooms.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Data\image\icon\root.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Data\image\icon\settings.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Data\image\icon\wnd_btn_back.png" />
    <Resource Include="Data\image\icon\wnd_btn_close.png" />
    <Resource Include="Data\image\icon\wnd_btn_max.png" />
    <Resource Include="Data\image\icon\wnd_btn_min.png" />
    <Resource Include="Data\image\icon\wnd_btn_normal.png" />
    <Resource Include="Data\image\ind.png" />
    <Resource Include="Data\image\logo13.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Data\image\N2NGO_Logo_GO.png" />
    <Resource Include="Data\image\N2NGO_Logo_N2N.png" />
    <Resource Include="Data\image\N2NGO_Logo_N2N_Border.png" />
    <Resource Include="Data\image\N2NGO_Logo_Warpper.png" />
    <Resource Include="Data\image\Preview.jpg" />
    <Resource Include="Data\image\Release.jpg" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\N2Nmc_Protocol\N2Nmc_Protocol.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Data\BinRef\Windows\N2NmcClientUpdate.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\BinRef\Windows\n2n\edge.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\BinRef\Windows\n2n\edge.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\NewsOffline.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\TAP-Windows.zip">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\TapWindowsInstaller\9.21.2.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\TapWindowsInstaller\openvpn.cer">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\TapWindowsInstaller\x32\OemVista.inf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\TapWindowsInstaller\x32\tap0901.cat">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\TapWindowsInstaller\x32\tap0901.sys">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\TapWindowsInstaller\x32\tapinstall.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\TapWindowsInstaller\x64\OemVista.inf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\TapWindowsInstaller\x64\tap0901.cat">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\TapWindowsInstaller\x64\tap0901.sys">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\TapWindowsInstaller\x64\tapinstall.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\BinRef\Windows\WinIPBroadcast\WinIPBroadcast.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="TAP-Windows\9.21.2.exe">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="TAP-Windows\openvpn.cer">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="TAP-Windows\x32\OemVista.inf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="TAP-Windows\x32\tap0901.cat">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="TAP-Windows\x32\tap0901.sys">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="TAP-Windows\x32\tapinstall.exe">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="TAP-Windows\x64\OemVista.inf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="TAP-Windows\x64\tap0901.cat">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="TAP-Windows\x64\tap0901.sys">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="TAP-Windows\x64\tapinstall.exe">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\MainResc.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>MainResc.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\MainResc.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>MainResc.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Data\BinRef\Linux\" />
    <Folder Include="Data\BinRef\Windows\n2n\" />
    <Folder Include="Resources\MainResc\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\.editorconfig" Link=".editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="HandyControl" Version="3.4.0" />
    <PackageReference Include="ImageProcessor" Version="2.9.0" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.4" />
  </ItemGroup>

</Project>
