<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Label="Globals">
    <WebView2LoaderPreference>Dynamic</WebView2LoaderPreference>
  </PropertyGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows10.0.18362.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <Platforms>AnyCPU;x64;x86</Platforms>
    <ApplicationIcon>Data\Images\N2N GO.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <SignAssembly>False</SignAssembly>
    <PackAsTool>False</PackAsTool>
    <IncludeSymbols>False</IncludeSymbols>
    <AssemblyVersion>4.0.1.1</AssemblyVersion>
    <Copyright>Copyright © 2024 LGF-Studio. All rights reserved.</Copyright>
    <FileVersion>4.0.1.1</FileVersion>
    <Description>N2N GO
</Description>
    <Title>$(AssemblyName)</Title>
    <PackageProjectUrl>https://gitee.com/xue-jiangbin/n2nmc</PackageProjectUrl>
    <PackageIcon>N2NGO.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://gitee.com/xue-jiangbin/n2nmc</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>p2p;n2n;c#;n2nmc;n2ngo;lgf-sutdio</PackageTags>
    <NeutralLanguage>en</NeutralLanguage>
    <PackageReleaseNotes>N2N GO Client</PackageReleaseNotes>
    <Authors>LGF-Studio</Authors>
    <EnableNETAnalyzers>True</EnableNETAnalyzers>
    <RootNamespace>$(MSBuildProjectName.Replace(" ", ""))</RootNamespace>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <AnalysisLevel>6.0</AnalysisLevel>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Resources\MainResc\**" />
    <EmbeddedResource Remove="Resources\MainResc\**" />
    <None Remove="Resources\MainResc\**" />
    <Page Remove="Resources\MainResc\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Data\Images\AdminMember.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Data\Images\N2N GO.ico" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Data\Fonts\CascadiaMono.ttf" />
    <Resource Include="Data\Fonts\Roboto-Black.ttf" />
    <Resource Include="Data\Fonts\Roboto-BlackItalic.ttf" />
    <Resource Include="Data\Fonts\Roboto-Bold.ttf" />
    <Resource Include="Data\Fonts\Roboto-BoldItalic.ttf" />
    <Resource Include="Data\Fonts\Roboto-Italic.ttf" />
    <Resource Include="Data\Fonts\Roboto-Light.ttf" />
    <Resource Include="Data\Fonts\Roboto-LightItalic.ttf" />
    <Resource Include="Data\Fonts\Roboto-Medium.ttf" />
    <Resource Include="Data\Fonts\Roboto-MediumItalic.ttf" />
    <Resource Include="Data\Fonts\Roboto-Regular.ttf" />
    <Resource Include="Data\Fonts\Roboto-Thin.ttf" />
    <Resource Include="Data\Fonts\Roboto-ThinItalic.ttf" />
    <Resource Include="Data\Fonts\RobotoCondensed-Bold.ttf" />
    <Resource Include="Data\Fonts\RobotoCondensed-BoldItalic.ttf" />
    <Resource Include="Data\Fonts\RobotoCondensed-Italic.ttf" />
    <Resource Include="Data\Fonts\RobotoCondensed-Light.ttf" />
    <Resource Include="Data\Fonts\RobotoCondensed-LightItalic.ttf" />
    <Resource Include="Data\Fonts\RobotoCondensed-Regular.ttf" />
    <Resource Include="Data\Images\icon\daynight.png" />
    <Resource Include="Data\Images\icon\info.png" />
    <Resource Include="Data\Images\icon\join.png" />
    <Resource Include="Data\Images\icon\log.png" />
    <Resource Include="Data\Images\icon\room.png" />
    <Resource Include="Data\Images\icon\rooming.png" />
    <Resource Include="Data\Images\icon\rooms.png" />
    <Resource Include="Data\Images\icon\root.png" />
    <Resource Include="Data\Images\icon\settings.png" />
    <Resource Include="Data\Images\icon\wnd_btn_back.png" />
    <Resource Include="Data\Images\icon\wnd_btn_close.png" />
    <Resource Include="Data\Images\icon\wnd_btn_max.png" />
    <Resource Include="Data\Images\icon\wnd_btn_min.png" />
    <Resource Include="Data\Images\icon\wnd_btn_normal.png" />
    <Resource Include="Data\Images\AdminMember.png" />
    <Resource Include="Data\Images\Member.png" />
    <Resource Include="Data\Images\Members.png" />
    <Resource Include="Data\Images\N2N GO Debug.png" />
    <Resource Include="Data\Images\N2N GO Develop.png" />
    <Resource Include="Data\Images\N2N GO Organization.png" />
    <Resource Include="Data\Images\N2N GO Preview.png" />
    <Resource Include="Data\Images\N2N GO.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Data\FlagIcons\ad.svg" />
    <Resource Include="Data\FlagIcons\ae.svg" />
    <Resource Include="Data\FlagIcons\af.svg" />
    <Resource Include="Data\FlagIcons\ag.svg" />
    <Resource Include="Data\FlagIcons\ai.svg" />
    <Resource Include="Data\FlagIcons\al.svg" />
    <Resource Include="Data\FlagIcons\am.svg" />
    <Resource Include="Data\FlagIcons\ao.svg" />
    <Resource Include="Data\FlagIcons\aq.svg" />
    <Resource Include="Data\FlagIcons\ar.svg" />
    <Resource Include="Data\FlagIcons\as.svg" />
    <Resource Include="Data\FlagIcons\at.svg" />
    <Resource Include="Data\FlagIcons\au.svg" />
    <Resource Include="Data\FlagIcons\aw.svg" />
    <Resource Include="Data\FlagIcons\ax.svg" />
    <Resource Include="Data\FlagIcons\az.svg" />
    <Resource Include="Data\FlagIcons\ba.svg" />
    <Resource Include="Data\FlagIcons\bb.svg" />
    <Resource Include="Data\FlagIcons\bd.svg" />
    <Resource Include="Data\FlagIcons\be.svg" />
    <Resource Include="Data\FlagIcons\bf.svg" />
    <Resource Include="Data\FlagIcons\bg.svg" />
    <Resource Include="Data\FlagIcons\bh.svg" />
    <Resource Include="Data\FlagIcons\bi.svg" />
    <Resource Include="Data\FlagIcons\bj.svg" />
    <Resource Include="Data\FlagIcons\bl.svg" />
    <Resource Include="Data\FlagIcons\bm.svg" />
    <Resource Include="Data\FlagIcons\bn.svg" />
    <Resource Include="Data\FlagIcons\bo.svg" />
    <Resource Include="Data\FlagIcons\bq.svg" />
    <Resource Include="Data\FlagIcons\br.svg" />
    <Resource Include="Data\FlagIcons\bs.svg" />
    <Resource Include="Data\FlagIcons\bt.svg" />
    <Resource Include="Data\FlagIcons\bv.svg" />
    <Resource Include="Data\FlagIcons\bw.svg" />
    <Resource Include="Data\FlagIcons\by.svg" />
    <Resource Include="Data\FlagIcons\bz.svg" />
    <Resource Include="Data\FlagIcons\ca.svg" />
    <Resource Include="Data\FlagIcons\cc.svg" />
    <Resource Include="Data\FlagIcons\cd.svg" />
    <Resource Include="Data\FlagIcons\cf.svg" />
    <Resource Include="Data\FlagIcons\cg.svg" />
    <Resource Include="Data\FlagIcons\ch.svg" />
    <Resource Include="Data\FlagIcons\ci.svg" />
    <Resource Include="Data\FlagIcons\ck.svg" />
    <Resource Include="Data\FlagIcons\cl.svg" />
    <Resource Include="Data\FlagIcons\cm.svg" />
    <Resource Include="Data\FlagIcons\cn.svg" />
    <Resource Include="Data\FlagIcons\co.svg" />
    <Resource Include="Data\FlagIcons\cr.svg" />
    <Resource Include="Data\FlagIcons\cu.svg" />
    <Resource Include="Data\FlagIcons\cv.svg" />
    <Resource Include="Data\FlagIcons\cw.svg" />
    <Resource Include="Data\FlagIcons\cx.svg" />
    <Resource Include="Data\FlagIcons\cy.svg" />
    <Resource Include="Data\FlagIcons\cz.svg" />
    <Resource Include="Data\FlagIcons\de.svg" />
    <Resource Include="Data\FlagIcons\dj.svg" />
    <Resource Include="Data\FlagIcons\dk.svg" />
    <Resource Include="Data\FlagIcons\dm.svg" />
    <Resource Include="Data\FlagIcons\do.svg" />
    <Resource Include="Data\FlagIcons\dz.svg" />
    <Resource Include="Data\FlagIcons\ec.svg" />
    <Resource Include="Data\FlagIcons\ee.svg" />
    <Resource Include="Data\FlagIcons\eg.svg" />
    <Resource Include="Data\FlagIcons\eh.svg" />
    <Resource Include="Data\FlagIcons\er.svg" />
    <Resource Include="Data\FlagIcons\es.svg" />
    <Resource Include="Data\FlagIcons\et.svg" />
    <Resource Include="Data\FlagIcons\fi.svg" />
    <Resource Include="Data\FlagIcons\fj.svg" />
    <Resource Include="Data\FlagIcons\fk.svg" />
    <Resource Include="Data\FlagIcons\fm.svg" />
    <Resource Include="Data\FlagIcons\fo.svg" />
    <Resource Include="Data\FlagIcons\fr.svg" />
    <Resource Include="Data\FlagIcons\ga.svg" />
    <Resource Include="Data\FlagIcons\gb-eng.svg" />
    <Resource Include="Data\FlagIcons\gb-nir.svg" />
    <Resource Include="Data\FlagIcons\gb-sct.svg" />
    <Resource Include="Data\FlagIcons\gb-wls.svg" />
    <Resource Include="Data\FlagIcons\gb.svg" />
    <Resource Include="Data\FlagIcons\gd.svg" />
    <Resource Include="Data\FlagIcons\ge.svg" />
    <Resource Include="Data\FlagIcons\gf.svg" />
    <Resource Include="Data\FlagIcons\gg.svg" />
    <Resource Include="Data\FlagIcons\gh.svg" />
    <Resource Include="Data\FlagIcons\gi.svg" />
    <Resource Include="Data\FlagIcons\gl.svg" />
    <Resource Include="Data\FlagIcons\gm.svg" />
    <Resource Include="Data\FlagIcons\gn.svg" />
    <Resource Include="Data\FlagIcons\gp.svg" />
    <Resource Include="Data\FlagIcons\gq.svg" />
    <Resource Include="Data\FlagIcons\gr.svg" />
    <Resource Include="Data\FlagIcons\gs.svg" />
    <Resource Include="Data\FlagIcons\gt.svg" />
    <Resource Include="Data\FlagIcons\gu.svg" />
    <Resource Include="Data\FlagIcons\gw.svg" />
    <Resource Include="Data\FlagIcons\gy.svg" />
    <Resource Include="Data\FlagIcons\hk.svg" />
    <Resource Include="Data\FlagIcons\hm.svg" />
    <Resource Include="Data\FlagIcons\hn.svg" />
    <Resource Include="Data\FlagIcons\hr.svg" />
    <Resource Include="Data\FlagIcons\ht.svg" />
    <Resource Include="Data\FlagIcons\hu.svg" />
    <Resource Include="Data\FlagIcons\id.svg" />
    <Resource Include="Data\FlagIcons\ie.svg" />
    <Resource Include="Data\FlagIcons\il.svg" />
    <Resource Include="Data\FlagIcons\im.svg" />
    <Resource Include="Data\FlagIcons\in.svg" />
    <Resource Include="Data\FlagIcons\io.svg" />
    <Resource Include="Data\FlagIcons\iq.svg" />
    <Resource Include="Data\FlagIcons\ir.svg" />
    <Resource Include="Data\FlagIcons\is.svg" />
    <Resource Include="Data\FlagIcons\it.svg" />
    <Resource Include="Data\FlagIcons\je.svg" />
    <Resource Include="Data\FlagIcons\jm.svg" />
    <Resource Include="Data\FlagIcons\jo.svg" />
    <Resource Include="Data\FlagIcons\jp.svg" />
    <Resource Include="Data\FlagIcons\ke.svg" />
    <Resource Include="Data\FlagIcons\kg.svg" />
    <Resource Include="Data\FlagIcons\kh.svg" />
    <Resource Include="Data\FlagIcons\ki.svg" />
    <Resource Include="Data\FlagIcons\km.svg" />
    <Resource Include="Data\FlagIcons\kn.svg" />
    <Resource Include="Data\FlagIcons\kp.svg" />
    <Resource Include="Data\FlagIcons\kr.svg" />
    <Resource Include="Data\FlagIcons\kw.svg" />
    <Resource Include="Data\FlagIcons\ky.svg" />
    <Resource Include="Data\FlagIcons\kz.svg" />
    <Resource Include="Data\FlagIcons\la.svg" />
    <Resource Include="Data\FlagIcons\lb.svg" />
    <Resource Include="Data\FlagIcons\lc.svg" />
    <Resource Include="Data\FlagIcons\li.svg" />
    <Resource Include="Data\FlagIcons\lk.svg" />
    <Resource Include="Data\FlagIcons\lr.svg" />
    <Resource Include="Data\FlagIcons\ls.svg" />
    <Resource Include="Data\FlagIcons\lt.svg" />
    <Resource Include="Data\FlagIcons\lu.svg" />
    <Resource Include="Data\FlagIcons\lv.svg" />
    <Resource Include="Data\FlagIcons\ly.svg" />
    <Resource Include="Data\FlagIcons\ma.svg" />
    <Resource Include="Data\FlagIcons\mc.svg" />
    <Resource Include="Data\FlagIcons\md.svg" />
    <Resource Include="Data\FlagIcons\me.svg" />
    <Resource Include="Data\FlagIcons\mf.svg" />
    <Resource Include="Data\FlagIcons\mg.svg" />
    <Resource Include="Data\FlagIcons\mh.svg" />
    <Resource Include="Data\FlagIcons\mk.svg" />
    <Resource Include="Data\FlagIcons\ml.svg" />
    <Resource Include="Data\FlagIcons\mm.svg" />
    <Resource Include="Data\FlagIcons\mn.svg" />
    <Resource Include="Data\FlagIcons\mo.svg" />
    <Resource Include="Data\FlagIcons\mp.svg" />
    <Resource Include="Data\FlagIcons\mq.svg" />
    <Resource Include="Data\FlagIcons\mr.svg" />
    <Resource Include="Data\FlagIcons\ms.svg" />
    <Resource Include="Data\FlagIcons\mt.svg" />
    <Resource Include="Data\FlagIcons\mu.svg" />
    <Resource Include="Data\FlagIcons\mv.svg" />
    <Resource Include="Data\FlagIcons\mw.svg" />
    <Resource Include="Data\FlagIcons\mx.svg" />
    <Resource Include="Data\FlagIcons\my.svg" />
    <Resource Include="Data\FlagIcons\mz.svg" />
    <Resource Include="Data\FlagIcons\na.svg" />
    <Resource Include="Data\FlagIcons\nc.svg" />
    <Resource Include="Data\FlagIcons\ne.svg" />
    <Resource Include="Data\FlagIcons\nf.svg" />
    <Resource Include="Data\FlagIcons\ng.svg" />
    <Resource Include="Data\FlagIcons\ni.svg" />
    <Resource Include="Data\FlagIcons\nl.svg" />
    <Resource Include="Data\FlagIcons\no.svg" />
    <Resource Include="Data\FlagIcons\np.svg" />
    <Resource Include="Data\FlagIcons\nr.svg" />
    <Resource Include="Data\FlagIcons\nu.svg" />
    <Resource Include="Data\FlagIcons\nz.svg" />
    <Resource Include="Data\FlagIcons\om.svg" />
    <Resource Include="Data\FlagIcons\pa.svg" />
    <Resource Include="Data\FlagIcons\pe.svg" />
    <Resource Include="Data\FlagIcons\pf.svg" />
    <Resource Include="Data\FlagIcons\pg.svg" />
    <Resource Include="Data\FlagIcons\ph.svg" />
    <Resource Include="Data\FlagIcons\pk.svg" />
    <Resource Include="Data\FlagIcons\pl.svg" />
    <Resource Include="Data\FlagIcons\pm.svg" />
    <Resource Include="Data\FlagIcons\pn.svg" />
    <Resource Include="Data\FlagIcons\pr.svg" />
    <Resource Include="Data\FlagIcons\ps.svg" />
    <Resource Include="Data\FlagIcons\pt.svg" />
    <Resource Include="Data\FlagIcons\pw.svg" />
    <Resource Include="Data\FlagIcons\py.svg" />
    <Resource Include="Data\FlagIcons\qa.svg" />
    <Resource Include="Data\FlagIcons\re.svg" />
    <Resource Include="Data\FlagIcons\ro.svg" />
    <Resource Include="Data\FlagIcons\rs.svg" />
    <Resource Include="Data\FlagIcons\ru.svg" />
    <Resource Include="Data\FlagIcons\rw.svg" />
    <Resource Include="Data\FlagIcons\sa.svg" />
    <Resource Include="Data\FlagIcons\sb.svg" />
    <Resource Include="Data\FlagIcons\sc.svg" />
    <Resource Include="Data\FlagIcons\sd.svg" />
    <Resource Include="Data\FlagIcons\se.svg" />
    <Resource Include="Data\FlagIcons\sg.svg" />
    <Resource Include="Data\FlagIcons\sh.svg" />
    <Resource Include="Data\FlagIcons\si.svg" />
    <Resource Include="Data\FlagIcons\sj.svg" />
    <Resource Include="Data\FlagIcons\sk.svg" />
    <Resource Include="Data\FlagIcons\sl.svg" />
    <Resource Include="Data\FlagIcons\sm.svg" />
    <Resource Include="Data\FlagIcons\sn.svg" />
    <Resource Include="Data\FlagIcons\so.svg" />
    <Resource Include="Data\FlagIcons\sr.svg" />
    <Resource Include="Data\FlagIcons\ss.svg" />
    <Resource Include="Data\FlagIcons\st.svg" />
    <Resource Include="Data\FlagIcons\sv.svg" />
    <Resource Include="Data\FlagIcons\sx.svg" />
    <Resource Include="Data\FlagIcons\sy.svg" />
    <Resource Include="Data\FlagIcons\sz.svg" />
    <Resource Include="Data\FlagIcons\tc.svg" />
    <Resource Include="Data\FlagIcons\td.svg" />
    <Resource Include="Data\FlagIcons\tf.svg" />
    <Resource Include="Data\FlagIcons\tg.svg" />
    <Resource Include="Data\FlagIcons\th.svg" />
    <Resource Include="Data\FlagIcons\tj.svg" />
    <Resource Include="Data\FlagIcons\tk.svg" />
    <Resource Include="Data\FlagIcons\tl.svg" />
    <Resource Include="Data\FlagIcons\tm.svg" />
    <Resource Include="Data\FlagIcons\tn.svg" />
    <Resource Include="Data\FlagIcons\to.svg" />
    <Resource Include="Data\FlagIcons\tr.svg" />
    <Resource Include="Data\FlagIcons\tt.svg" />
    <Resource Include="Data\FlagIcons\tv.svg" />
    <Resource Include="Data\FlagIcons\tw.svg" />
    <Resource Include="Data\FlagIcons\tz.svg" />
    <Resource Include="Data\FlagIcons\ua.svg" />
    <Resource Include="Data\FlagIcons\ug.svg" />
    <Resource Include="Data\FlagIcons\um.svg" />
    <Resource Include="Data\FlagIcons\us.svg" />
    <Resource Include="Data\FlagIcons\uy.svg" />
    <Resource Include="Data\FlagIcons\uz.svg" />
    <Resource Include="Data\FlagIcons\va.svg" />
    <Resource Include="Data\FlagIcons\vc.svg" />
    <Resource Include="Data\FlagIcons\ve.svg" />
    <Resource Include="Data\FlagIcons\vg.svg" />
    <Resource Include="Data\FlagIcons\vi.svg" />
    <Resource Include="Data\FlagIcons\vn.svg" />
    <Resource Include="Data\FlagIcons\vu.svg" />
    <Resource Include="Data\FlagIcons\wf.svg" />
    <Resource Include="Data\FlagIcons\ws.svg" />
    <Resource Include="Data\FlagIcons\xk.svg" />
    <Resource Include="Data\FlagIcons\ye.svg" />
    <Resource Include="Data\FlagIcons\yt.svg" />
    <Resource Include="Data\FlagIcons\za.svg" />
    <Resource Include="Data\FlagIcons\zm.svg" />
    <Resource Include="Data\FlagIcons\zw.svg" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Data\Images\About.png" />
    <Resource Include="Data\Images\Advanced.png" />
    <Resource Include="Data\Images\CheckUpdate.png" />
    <Resource Include="Data\Images\Clienting.png" />
    <Resource Include="Data\Images\Community.png" />
    <Resource Include="Data\Images\Hosting.png" />
    <Resource Include="Data\Images\logo13.ico">
      <CopyToOutputDirectory></CopyToOutputDirectory>
    </Resource>
    <Resource Include="Data\Images\N2NGO_Logo_GO.png" />
    <Resource Include="Data\Images\N2NGO_Logo_N2N.png" />
    <Resource Include="Data\Images\N2NGO_Logo_N2N_Border.png" />
    <Resource Include="Data\Images\N2NGO_Logo_Warpper.png" />
    <Resource Include="Data\Images\Storage.png" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Data\BinRef\Windows\n2n\edge.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\Images\N2NGO.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Data\BinRef\Linux\" />
    <Folder Include="Data\BinRef\Windows\n2n\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\.editorconfig" Link=".editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="HandyControl" Version="3.5.1">
      <GeneratePathProperty></GeneratePathProperty>
    </PackageReference>
    <PackageReference Include="iNKORE.UI.WPF.Modern" Version="0.9.30" />
    <PackageReference Include="MagicEffects" Version="1.0.0">
      <NoWarn>NU1701</NoWarn>
    </PackageReference>
    <PackageReference Include="SharpVectors" Version="1.8.4.2" />
    <PackageReference Include="Walterlv.Themes.FluentDesign" Version="7.9.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\N2NGO Core\N2NGO Core.csproj" />
  </ItemGroup>

</Project>
